### PR TITLE
set new record post to a generic id

### PR DESCRIPTION
**Pull request by cryophallion**
And another quick one.

Since I assume you always use id as your pkid, I don't assume you've run into this...

If you leave this as just 'id', then everything in your controller can be left nice and generic as id, and the model can set the proper pkid, as it should. This one line forces you to change every instance of the $id in the edit class though, and the views, to the named pkid in the model. It would be better to leave this mostly generic, to keep things simple.

This one is far more up for discussion, but I wanted to present it as an option

### CODE REVIEW

**Comment by jordanlev** [comment]
Thanks, nice catch!

**Comment by jordanlev** [comment]
No, wait... I misunderstood... I thought you were changing a hardcoded `'id` to the `$this->pkid` variable... but you were doing the opposite instead. I don't understand why you'd want to do this, as it breaks the intended functionality of being able to set the primary key field name. If there's a problem you're having due to this, there is probably a better fix than this workaround (which will break other things).

I'm going to revert this commit. If you want to explain in more detail the problem you're having I can try to think of a better solution for you.

**Comment by cryophallion** [comment]
Actually, the only other contributor fixed the bug you were thinking of... the only issue is, it's not actually a bug. 

I will happily explain:
Let's say you like doing your schema like the C5 internal schema, where all IDs have a distinct prefix for ease of queries, etc. So, let's say there is a `Event` table and  a `Location` table for this particular situation. The id of the `Event` table is `eID` and the id of `Location` is `lID`. 

Now, using your code as is, we now have to go into the controller and view and model and replace ALL `id` calls with `eID` and `lID`. And then we add 12 more tables. EVERY SINGLE ONE (and there are a lot, trust me, I started on it for numerous pages) has to now have a custom controller and view, replacing every `id` call with the appropriate one for the schema. Frankly, that blows apart every aspect of the usability of the code.

However, say you were to hardcode that one line as `id`. Then no line of code for the view or controller has to be changed anymore. They stay all as `id`. And then when it gets to the Model, THAT is where it is properly mapped to the `pkid` field. Exactly where that call should happen, where the database gets pulled in, and where the `pkid` is set just once.

The `id` can safely and logically be made generic. And then it gets mapped from `id` to `pkid` in the model. If you are using `id` as the id field, you would never see it. But use distinct id fields, and the difference becomes night and day. It goes from being a flexible generic class to something that is way too static and has to get gutted for every dashboard.

**Comment by jordanlev** [comment]
Hmm... I think I understand what you're describing. I'm going to need to look at this in more detail though. Since this is boilerplate code, my intention is that one would go through and replace the string `'id'` with whatever their primary key field name actually is (which should be very easy using your text editor or IDE "find-and-replace" functionality). This is not intended to be a generic re-usable library, but rather an example of how you can build these things in Concrete5.

But of course if it's a total nightmare to use effectively on projects where the id field has a different name, then I would like to come up with a solution that addresses it.

I just need to test this out and think through the ramifications.

Thanks for taking the time to explain it.

**Comment by cryophallion** [comment]
Thanks for taking the time to consider it. Sorry for all these issues, just trying to help out, and give back to a worthwhile project. Thanks again for all your work, and being willing to listen to my thoughts and concerns.

**Pull request merged**
